# Select image from https://hub.docker.com/_/php/
image: php:5.6
 
# Select what we should cache
cache:
  paths:
  - vendor/
 
before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq
 
# Install composer
- curl -sS https://getcomposer.org/installer | php
 
# Install all project dependencies
- php composer.phar install

- ls

 
 
# We test PHP7 with MySQL, but we allow it to fail
test:php7:
  image: php:7
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text
  allow_failure: false